<template>
    <div id="sparc-record-detail">
        <div id="left-content-column">
            <div class="content-container__info__title"> </div>
            <div class="content-container__info__text">The Sparc Dataportal is an easily accessible resource to find, visualize and access data generated by the NIH SPARC project.</div>
        </div>
        <div id="right-content-column">
            <div class="sparc-details">
            </div>
                
        </div>
    </div>
</template>

<script>

export default {
    components: {
    },
    name: 'sparc-record-detail',
    

    data() {
      return {
        id: ''
      }
    },
    computed: {
       
    },
    watch: {
        '$route' (to, from) {
            this.id = this.$route.params.id
        }
    },

    props: {

       
    },
    methods: {
        
    },
    mounted () {
         this.id = this.$route.params.id
    },

}
</script>

<style lang="scss" scoped>

    #sparc-record-detail {
        display: flex;
        flex-direction: row;
        width: 100%;
    }


</style>
